# Generated by Django 5.2.3 on 2025-09-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_mobile',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='invoice',
            name='city',
            field=models.CharField(default='mad', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='country',
            field=models.CharField(default='mad', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='mad', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='pincode',
            field=models.PositiveIntegerField(default='625011'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.CharField(default='ind', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
