# Generated by Django 5.2.3 on 2025-09-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0002_rename_customer_name_invoice_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
